fix: script on macos

diff --git a/.github/workflows/check.yaml b/.github/workflows/check.yaml
--- a/.github/workflows/check.yaml
+++ b/.github/workflows/check.yaml
@@ -12,11 +12,8 @@ on:
       - master
 
 jobs:
-  test-unix:
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest]
-    runs-on: ${{ matrix.os }}
+  test-ubuntu:
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -72,3 +69,29 @@ jobs:
           tt run --font-path "$FONT_DIR" --no-fail-fast --use-system-fonts
           tt run --no-fail-fast --use-system-fonts fontsets/windows
         shell: pwsh
+
+  test-macos:
+    runs-on: macos-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Setup Typst
+        uses: typst-community/setup-typst@v3
+      - name: Install tytanic
+        uses: taiki-e/cache-cargo-install-action@v2
+        with:
+          tool: tytanic@0.2.2
+      - name: Install Fandol fonts
+        run: |
+          FONT_DIR=~/Library/Fonts/Fandol
+          mkdir -p $FONT_DIR
+          curl -L "https://mirrors.ctan.org/fonts/fandol.zip" -o fandol.zip
+          unzip fandol.zip -d $FONT_DIR && rm fandol.zip
+          if typst fonts | grep -q Fandol; then
+            echo "Fandol fonts installed successfully."
+          else
+            echo "Fandol fonts installation failed."
+            exit 1
+          fi
+      - name: Run CTyp tests
+        run: tt run --no-fail-fast --use-system-fonts
